@startuml
class AnalyzeDependenciesCommand {
}

class DependencyDumper {
}

class DirectedGraph {
}

class CycleDetector {
}

class RuleViolationDetector {
}

note top of AnalyzeDependenciesCommand
  Command class for CLI.
  This receive search directory, rule file, options, etc...
end note

AnalyzeDependenciesCommand "1" -- "1" DependencyDumper
AnalyzeDependenciesCommand -- DirectedGraph
DependencyDumper -- DirectedGraph: create
AnalyzeDependenciesCommand *-- CycleDetector
AnalyzeDependenciesCommand *-- RuleViolationDetector

namespace PHPStan {
  class Dependency\DumpDependenciesCommand {
  }

  class Dependency\DependencyDumper {
  }

  .DependencyDumper "1" *-- "1" Dependency\DependencyDumper
  Dependency\DumpDependenciesCommand "1" *-- "1" Dependency\DependencyDumper
}

namespace Fhaculty {
  class Graph\Graph {
  }

  .DirectedGraph "1" *-- "1" Graph\Graph
}

/'
class CollectionBuilder {
  - LogFile file
}

class ItemCollection {
  - array items
}

class View {
  - string dimensions
  - array columns
}

class SplFileObject {
}

class LogFile {
  - string path
  - ParserInterface parser
}

class Item {
  - LogFile file
  - int linePos
}

class ItemInterface {
}

class ApacheLogParser {
  - string format
}

class LtsvParser {
}

class ParserInterface {
}

CollectionBuilder ..> ItemCollection : create
ItemCollection o-- Item
Item <|.. ItemInterface
Item "1..n" -- "1" LogFile
ApacheLogParser <|.. ParserInterface
LtsvParser <|.. ParserInterface
LogFile <|-- SplFileObject
LogFile "0..n" -- "1" ParserInterface
ItemCollection <..> View : create
'/

@enduml
